### ISSUE TITLE
Android SDK Release mode proguard issue

### ISSUE THREAD

**Issue by payodasam** [testfairy/docs#389]
We are getting the following error while generating an android build in release mode. This issue reproduced while generating build in MAC OS but not reproducible in Linux(Ubuntu 18.04).

`D8: Class content provided for type descriptor com.testfairy.utils.E actually defines class com.testfairy.utils.e
20:26:39 D8: Class content provided for type descriptor com.testfairy.utils.E actually defines class com.testfairy.utils.e
20:27:05 org.gradle.workers.WorkerExecutionException: There were multiple failures while executing work items
20:27:05 	at org.gradle.workers.internal.DefaultWorkerExecutor.workerExecutionException(DefaultWorkerExecutor.java:160)`

**Comment by gmegidish** [comment]
Hey @payodasam . I am sorry to be replying so late. Our support team is always here to help. This is the documentation repository. About the problem you're facing, it _might_ happen on Windows and Mac because of case insensitive filesystems, and a tool that instruments the classes.dex of our sdk. When it unpacks class called "e", it overwrites it with "E". Latest Android SDK handles these cases, you can either fix the tooling you're using, or (better) upgrade to the latest SDK. I hope this helps!
